// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#include "../ui.h"

void ui_ticker_screen_init(void)
{
ui_ticker = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ticker, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImageBG = lv_img_create(ui_ticker);
lv_img_set_src(ui_ImageBG, &ui_img_213572400);
lv_obj_set_width( ui_ImageBG, LV_SIZE_CONTENT);  /// 536
lv_obj_set_height( ui_ImageBG, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_ImageBG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageBG, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageBG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_date = lv_label_create(ui_ticker);
lv_obj_set_width( ui_Label_date, 131);
lv_obj_set_height( ui_Label_date, 33);
lv_obj_set_x( ui_Label_date, 13 );
lv_obj_set_y( ui_Label_date, 10 );
lv_label_set_text(ui_Label_date,"04-09-24");
lv_obj_set_style_text_letter_space(ui_Label_date, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_date, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_date, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_date, &ui_font_Font25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_time = lv_label_create(ui_ticker);
lv_obj_set_width( ui_Label_time, 119);
lv_obj_set_height( ui_Label_time, 33);
lv_obj_set_x( ui_Label_time, 164 );
lv_obj_set_y( ui_Label_time, 10 );
lv_label_set_text(ui_Label_time,"04:00 PM");
lv_obj_set_style_text_color(ui_Label_time, lv_color_hex(0xFFCA41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_time, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_time, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_time, &ui_font_Font25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Price_Rate = lv_label_create(ui_ticker);
lv_obj_set_width( ui_Label_Price_Rate, 520);
lv_obj_set_height( ui_Label_Price_Rate, 107);
lv_obj_set_x( ui_Label_Price_Rate, 0 );
lv_obj_set_y( ui_Label_Price_Rate, -6 );
lv_obj_set_align( ui_Label_Price_Rate, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label_Price_Rate,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_Label_Price_Rate,"00000.00");
lv_obj_set_style_text_color(ui_Label_Price_Rate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Price_Rate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_Price_Rate, -5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_Price_Rate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Price_Rate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Price_Rate, &ui_font_Font100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPricehigh = ui_LabelPricehigh_create(ui_ticker);
lv_obj_set_x( ui_LabelPricehigh, -94 );
lv_obj_set_y( ui_LabelPricehigh, 87 );

ui_labelPriceLow = ui_labelPriceLow_create(ui_ticker);
lv_obj_set_x( ui_labelPriceLow, 160 );
lv_obj_set_y( ui_labelPriceLow, 87 );

ui_Label_text = lv_label_create(ui_ticker);
lv_obj_set_width( ui_Label_text, 120);
lv_obj_set_height( ui_Label_text, 26);
lv_obj_set_x( ui_Label_text, 404 );
lv_obj_set_y( ui_Label_text, 13 );
lv_label_set_text(ui_Label_text,"Bitcoin");
lv_obj_add_flag( ui_Label_text, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_Label_text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_text, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_text, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_text, &ui_font_Font25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_symbol = lv_img_create(ui_ticker);
lv_img_set_src(ui_img_symbol, &ui_img_ethnew_png);
lv_obj_set_width( ui_img_symbol, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_img_symbol, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_img_symbol, 130 );
lv_obj_set_y( ui_img_symbol, -94 );
lv_obj_set_align( ui_img_symbol, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_symbol, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_symbol, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_img_symbol,264);

ui_img_symbol_btc = lv_img_create(ui_ticker);
lv_img_set_src(ui_img_symbol_btc, &ui_img_images_btc_png);
lv_obj_set_width( ui_img_symbol_btc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_img_symbol_btc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_img_symbol_btc, 139 );
lv_obj_set_y( ui_img_symbol_btc, -93 );
lv_obj_set_align( ui_img_symbol_btc, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_symbol_btc, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_symbol_btc, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_no_wifi = lv_img_create(ui_ticker);
lv_img_set_src(ui_no_wifi, &ui_img_376556310);
lv_obj_set_width( ui_no_wifi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_no_wifi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_no_wifi, 53 );
lv_obj_set_y( ui_no_wifi, -94 );
lv_obj_set_align( ui_no_wifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_no_wifi, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_no_wifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_no_websocket = lv_img_create(ui_ticker);
lv_img_set_src(ui_no_websocket, &ui_img_msg_png);
lv_obj_set_width( ui_no_websocket, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_no_websocket, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_no_websocket, 87 );
lv_obj_set_y( ui_no_websocket, -94 );
lv_obj_set_align( ui_no_websocket, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_no_websocket, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_no_websocket, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
