// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#ifndef _BTC_TICKER_UI_COMP_HOOK_H
#define _BTC_TICKER_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_LabelPricehigh_create_hook( lv_obj_t *comp );
void ui_comp_Labeldate_create_hook( lv_obj_t *comp );
void ui_comp_labelPriceLow_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
