// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#include "../ui.h"


// COMPONENT LabelPricehigh

lv_obj_t *ui_LabelPricehigh_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_LabelPricehigh;
cui_LabelPricehigh = lv_label_create(comp_parent);
lv_obj_set_width( cui_LabelPricehigh, 203);
lv_obj_set_height( cui_LabelPricehigh, 40);
lv_obj_set_x( cui_LabelPricehigh, -94 );
lv_obj_set_y( cui_LabelPricehigh, 87 );
lv_obj_set_align( cui_LabelPricehigh, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPricehigh,"00000.00");
lv_obj_set_style_text_color(cui_LabelPricehigh, lv_color_hex(0x4AF68B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_LabelPricehigh, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(cui_LabelPricehigh, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(cui_LabelPricehigh, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_LabelPricehigh, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPricehigh, &ui_font_Font38, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABELPRICEHIGH_NUM);
children[UI_COMP_LABELPRICEHIGH_LABELPRICEHIGH] = cui_LabelPricehigh;
lv_obj_add_event_cb(cui_LabelPricehigh, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_LabelPricehigh, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_LabelPricehigh_create_hook(cui_LabelPricehigh);
return cui_LabelPricehigh; 
}

