// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#ifndef _UI_COMP_LABELPRICELOW_H
#define _UI_COMP_LABELPRICELOW_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT labelPriceLow
#define UI_COMP_LABELPRICELOW_LABELPRICELOW 0
#define _UI_COMP_LABELPRICELOW_NUM 1
lv_obj_t *ui_labelPriceLow_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
