// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#include "../ui.h"


// COMPONENT Labeldate

lv_obj_t *ui_Labeldate_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Labeldate;
cui_Labeldate = lv_label_create(comp_parent);
lv_obj_set_width( cui_Labeldate, 131);
lv_obj_set_height( cui_Labeldate, 33);
lv_obj_set_x( cui_Labeldate, 13 );
lv_obj_set_y( cui_Labeldate, 10 );
lv_label_set_text(cui_Labeldate,"04-09-24");
lv_obj_set_style_text_letter_space(cui_Labeldate, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(cui_Labeldate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_Labeldate, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Labeldate, &ui_font_Font25, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABELDATE_NUM);
children[UI_COMP_LABELDATE_LABELDATE] = cui_Labeldate;
lv_obj_add_event_cb(cui_Labeldate, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Labeldate, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Labeldate_create_hook(cui_Labeldate);
return cui_Labeldate; 
}

