// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#include "../ui.h"


// COMPONENT labelPriceLow

lv_obj_t *ui_labelPriceLow_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_labelPriceLow;
cui_labelPriceLow = lv_label_create(comp_parent);
lv_obj_set_width( cui_labelPriceLow, 199);
lv_obj_set_height( cui_labelPriceLow, 40);
lv_obj_set_x( cui_labelPriceLow, 160 );
lv_obj_set_y( cui_labelPriceLow, 87 );
lv_obj_set_align( cui_labelPriceLow, LV_ALIGN_CENTER );
lv_label_set_text(cui_labelPriceLow,"00000.00");
lv_obj_set_style_text_color(cui_labelPriceLow, lv_color_hex(0xFF2829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_labelPriceLow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(cui_labelPriceLow, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(cui_labelPriceLow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_labelPriceLow, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_labelPriceLow, &ui_font_Font38, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABELPRICELOW_NUM);
children[UI_COMP_LABELPRICELOW_LABELPRICELOW] = cui_labelPriceLow;
lv_obj_add_event_cb(cui_labelPriceLow, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_labelPriceLow, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_labelPriceLow_create_hook(cui_labelPriceLow);
return cui_labelPriceLow; 
}

