// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#ifndef _UI_COMP_LABELPRICEHIGH_H
#define _UI_COMP_LABELPRICEHIGH_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT LabelPricehigh
#define UI_COMP_LABELPRICEHIGH_LABELPRICEHIGH 0
#define _UI_COMP_LABELPRICEHIGH_NUM 1
lv_obj_t *ui_LabelPricehigh_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
