// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_loading
void ui_loading_screen_init(void);
lv_obj_t *ui_loading;
lv_obj_t *ui_Image_logo1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Spinner1;


// SCREEN: ui_wifiProv
void ui_wifiProv_screen_init(void);
lv_obj_t *ui_wifiProv;
lv_obj_t *ui_Container_QR;
lv_obj_t *ui_TextArea;
lv_obj_t *ui_Image_logo;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Image_mask;


// SCREEN: ui_ticker
void ui_ticker_screen_init(void);
lv_obj_t *ui_ticker;
lv_obj_t *ui_ImageBG;
lv_obj_t *ui_Label_date;
lv_obj_t *ui_Label_time;
lv_obj_t *ui_Label_Price_Rate;
lv_obj_t *ui_LabelPricehigh;
lv_obj_t *ui_labelPriceLow;
lv_obj_t *ui_Label_text;
lv_obj_t *ui_img_symbol;
lv_obj_t *ui_img_symbol_btc;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1516409835[1] = {&ui_img_1283391855};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_loading_screen_init();
ui_wifiProv_screen_init();
ui_ticker_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_loading);
}
