// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#ifndef _BTC_TICKER_UI_H
#define _BTC_TICKER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_loading
void ui_loading_screen_init(void);
extern lv_obj_t *ui_loading;
extern lv_obj_t *ui_Image_logo1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Spinner1;
// SCREEN: ui_wifiProv
void ui_wifiProv_screen_init(void);
extern lv_obj_t *ui_wifiProv;
extern lv_obj_t *ui_Container_QR;
extern lv_obj_t *ui_TextArea;
extern lv_obj_t *ui_Image_logo;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Image_mask;
// SCREEN: ui_ticker
void ui_ticker_screen_init(void);
extern lv_obj_t *ui_ticker;
extern lv_obj_t *ui_ImageBG;
extern lv_obj_t *ui_Label_time;
extern lv_obj_t *ui_Label_Price_Rate;
extern lv_obj_t *ui_LabelPricehigh;
extern lv_obj_t *ui_labelPriceLow;
extern lv_obj_t *ui_Label_text;
extern lv_obj_t *ui_img_symbol;
extern lv_obj_t *ui_img_symbol_btc;
extern lv_obj_t *ui_no_wifi;
extern lv_obj_t *ui_no_websocket;
extern lv_obj_t *ui_Label_Battary;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_images_logo_png);   // assets/Images/Logo.png
LV_IMG_DECLARE( ui_img_1283391855);   // assets/Images/bg-2-2.png
LV_IMG_DECLARE( ui_img_213572400);   // assets/Images/BG-ticker.png
LV_IMG_DECLARE( ui_img_ethnew_png);   // assets/ethnew.png
LV_IMG_DECLARE( ui_img_images_btc_png);   // assets/Images/btc.png
LV_IMG_DECLARE( ui_img_376556310);   // assets/no-wifi.png
LV_IMG_DECLARE( ui_img_msg_png);   // assets/msg.png


LV_FONT_DECLARE( ui_font_Font100);
LV_FONT_DECLARE( ui_font_Font25);
LV_FONT_DECLARE( ui_font_Font38);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
